
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <param/param.h>
#include <param/param_list.h>
#include <vmem/vmem.h>
#include <vmem/vmem_ram.h>
#include <slash/slash.h>
#include <slash/optparse.h>
#include <slash/dflopt.h>

/* __attribute__((visibility("hidden"))) prevents the section symbols from linking with 
	the loading application (csh) when compiling an addin.
	In simple terms: When used alone, this means the addin must define at least 1 command,
	(so "__start_slash" will be generated by GCC) before it can use slash as a dependency.
    But when combined with 'weak' the value will be NULL, instead of linking with the sections in CSH. */
extern struct slash_command __start_slash __attribute__((visibility("hidden"), weak));
extern struct slash_command __stop_slash __attribute__((visibility("hidden"), weak));

extern param_t __start_param __attribute__((visibility("hidden"), weak));
extern param_t __stop_param __attribute__((visibility("hidden"), weak));

#if 0
/* __attribute__((constructor)) will run automatically when linking with the loading application, 
    but not arguments can be passed. */
__attribute__((constructor)) void libinit(void) {

}
#endif


/* slash_list_add() is declared 'weak' such that loaders without slash (such as PyCSH) 
    can still load parameter APMs (such as PSU drivers). */
__attribute__((weak)) extern int slash_list_add(struct slash_command * cmd);

__attribute__((visibility("default"), used))
void libmain(int argc, char ** argv) {
// void libmain(void) {

    if (slash_list_add != NULL) {  // If the loading application uses slash.
        for (struct slash_command * cmd = &__start_slash; cmd < &__stop_slash; cmd += 1) {
            slash_list_add(cmd);
        }
    }

    /* Check if we have parameter section defined */
    if (&__start_param != &__stop_param) {
        for (param_t * param = &__start_param; param < &__stop_param; param += 1) {
            // printf("name %s %p %p %x %p\n", param->name, param, param->addr, param->mask, &param->mask);
            int ret = param_list_add(param);
            // printf("Result %d\n", ret);
        }
    }
}
